apiVersion: apps/v1
kind: Deployment
metadata:
  name: developersdays-back-deployment
  labels:
    component: developersdays-back
spec:
  selector:
    matchLabels:
      component: developersdays-back
  template:
    metadata:
      labels:
        component: developersdays-back
    spec:
      containers:
      - name: developersdays-back
        image: developersdays2019euwacr.azurecr.io/developersdays/back-auth
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
